config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  devise_for :users
  resources :users, only: [:index, :show]
  resources :talk_concerts do
    member do
      get :room
    end
    resource :enrollments, only: [:create, :destroy]
    resource :voices,      only: [:create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource  :users,         only: [:create, :update, :destroy]
      resources :users,         only: [:index, :show]
      resources :talk_concerts, only: [:index, :create, :update, :destroy]
      resource  :sessions,      only: [:create, :destroy]
      resource  :enrollments,   only: [:create, :destroy]
      resource  :voices,        only: [:create, :destroy]
    end                                
  end
end

app/models/talk_concert.rb
class TalkConcert < ActiveRecord::Base
  resourcify
  include Authority::Abilities

  belongs_to :user
  has_many :enrollments, dependent: :destroy
  has_many :voices, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/api/v1/talk_concerts_controller.rb
class Api::V1::TalkConcertsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_with_token!, except: [ :index, :show ]

  def index
    @talk_concerts = TalkConcert.paginate(page: params[:page])
    render json: { result: "success", talk_concerts: @talk_concerts }
  end

  def show
    @talk_concert = TalkConcert.find(params[:id])

    if @talk_concert
      render json: { result: "success", talk_concert: @talk_concert }
    else
      render json: { result: "fail" }
    end
  end

  def create
    @talk_concert = TalkConcert.new(talk_concert_params)
    @talk_concert.user = current_user_with_token

    if @talk_concert.save
      render json: { result: "success", talk_concert: @talk_concert }
    else
      render json: { result: "fail", errors: @talk_concert.errors }
    end
  end

  def update
    @talk_concert = TalkConcert.find(params[:id])

    if current_user_with_token == @talk_concert.user
      if @talk_concert.update_attributes(talk_concert_params)
        render json: { result: "success", talk_concert: @talk_concert }
      else
        render json: { result: "fail", errors: @talk_concert.errors }
      end
    else
      render json: { result: "fail" }
    end
  end

  def destroy
    @talk_concert = TalkConcert.find(params[:id])

    if current_user_with_token == @talk_concert.user
      @talk_concert.destroy
      render json: { result: "success" }
    else
      render json: { result: "fail" }
    end
  end

  private

  def talk_concert_params
    params.require(:talk_concert).permit(:title, :start_time, :end_time, :location, :people_limit, :content, :enroll_start_time, :enroll_end_time)
  end
end

app/controllers/talk_concerts_controller.rb
class TalkConcertsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :enrolled_user?, only: [:room]

  def index
    @talk_concerts = TalkConcert.paginate(page: params[:page])
  end

  def show
    @talk_concert = TalkConcert.find(params[:id])
    @current_user_enrollment = @talk_concert.enrollments.find_by(user: current_user)
    @enrollments = @talk_concert.enrollments
  end

  def new
    @talk_concert = TalkConcert.new
  end

  def create
    @talk_concert = TalkConcert.new(talk_concert_params)
    @talk_concert.user = current_user

    if @talk_concert.save
      flash[:success] = "Talk concert made"
      redirect_to @talk_concert
    else
      render 'new'
    end
  end

  def edit
    @talk_concert = TalkConcert.find(params[:id])

    authorize_action_for @talk_concert
  end

  def update
    @talk_concert = TalkConcert.find(params[:id])

    authorize_action_for @talk_concert

    if @talk_concert.update_attributes(talk_concert_params)
      flash[:success] = "Talk concert updated"
      redirect_to @talk_concert
    else
      render 'edit'
    end
  end

  def destroy
    @talk_concert = TalkConcert.find(params[:id])

    authorize_action_for @talk_concert

    @talk_concert.destroy

    flash[:success] = "Talk concert deleted"
    redirect_to talk_concerts_url
  end

  def room
    @talk_concert = TalkConcert.find(params[:id])
    @current_user = current_user
    @current_user_voice = @talk_concert.voices.find_by(user: current_user)
    @voices = @talk_concert.voices
  end

  private

  def talk_concert_params
    params.require(:talk_concert).permit(:title, :start_time, :end_time, :location, :people_limit, :content, :enroll_start_time, :enroll_end_time)
  end
end

app/helpers/talk_concerts_helper.rb
module TalkConcertsHelper
end

app/views/talk_concerts/_form.html.erb
<%= form_for(@talk_concert) do |f| %>
  <% if @talk_concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk_concert.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @talk_concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class: "field">
    <%= f.label :title, "제목" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class: "field">
    <%= f.label :start_time, "시작시간" %><br>
    <div class="input-group date datetimepicker">
      <%= f.text_field :start_time, class: 'form-control', data: { date_format: "YYYY/MM/DD hh:mm A" } %>
      <div id="datetimepicker"></div>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
  </div>
  <div class: "field">
    <%= f.label :end_time, "종료시간" %><br>
    <div class="input-group date datetimepicker">
      <%= f.text_field :end_time, class: 'form-control', data: { date_format: "YYYY/MM/DD hh:mm A" } %>
      <div id="datetimepicker"></div>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
  </div>
  <div class: "field">
    <%= f.label :location, "장소" %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class: "field">
    <%= f.label :people_limit, "인원제한" %><br>
    <%= f.number_field :people_limit, class: "form-control" %>
  </div>
  <div class: "field">
    <%= f.label :content, "내용" %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class: "field">
    <%= f.label :enroll_start_time, "참여시작시간" %><br>
    <div class="input-group date datetimepicker">
      <%= f.text_field :enroll_start_time, class: 'form-control', data: { date_format: "YYYY/MM/DD hh:mm A" } %>
      <div id="datetimepicker"></div>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
  </div>
  <div class: "field">
    <%= f.label :enroll_end_time, "참여종료시간" %><br>
    <div class="input-group date datetimepicker">
      <%= f.text_field :enroll_end_time, class: 'form-control', data: { date_format: "YYYY/MM/DD hh:mm A" } %>
      <div id="datetimepicker"></div>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
  </div>
  <div class: "actions">
    <%= f.submit "저장", class: "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

<script type="text/javascript">
  $(function () {
    $('.datetimepicker').datetimepicker({
      sideBySide: true
    });
  });
</script>

app/views/talk_concerts/_talk_concert.html.erb
<tr>
  <td><%= talk_concert.user.name %></td>
  <td><%= link_to talk_concert.title, talk_concert %></td>
  <td><%= talk_concert.people_limit %></td>
  <td><%= time_ago_in_words(talk_concert.created_at) %> ago.</td>
  <td><%= talk_concert.location %></td>
</tr>

app/views/talk_concerts/edit.html.erb
<% provide(:title, "Edit talk concert") %>
<h1>Edit talk concert</h1>

<%= render 'form' %>

app/views/talk_concerts/index.html.erb
<% provide(:title, "All talk concerts") %>
<h1>All talk concerts</h1>

<%= will_paginate %>

<table class="table table-striped">
  <tbody>
    <tr>
      <td>강연자</td>
      <td>제목</td>
      <td>인원제한</td>
      <td>작성시간</td>
      <td>장소</td>
    </tr>
    <%= render @talk_concerts %>
  </tbody>
</table>

<%= will_paginate %>

<% if user_signed_in? %>
  <%= link_to 'New talk concert', new_talk_concert_path, class: "btn btn-primary" %>
<% end %>

app/views/talk_concerts/new.html.erb
<% provide(:title, "New talk concert") %>
<h1>New talk concert</h1>

<%= render 'form' %>

app/views/talk_concerts/room.html.erb
<div class="container">
  <h1><%= link_to @talk_concert.title, @talk_concert %> 방</h1>
  <% if current_user == @talk_concert.user %>
    <h2>발언권 신청자</h2>
    <%= render @voices %>
    <script src="http://www.playrtc.com/sdk/js/1.0.6/playrtc.min.js"></script>
    <div>
      <input type="text" id="channelId" placeholder="ChannelId를 입력하세요." value="">
      <button id="connectChannel">채널 입장</button>
      <button id="createChannel">채널 생성 및 입장</button>
    </div>
    <audio id="localAudio"></audio>
    <audio id="remoteAudio"></audio>
    <script type="text/javascript">
      conn = new PlayRTC({
        url: "http://172.20.10.3:5400",
        localVideoTarget: "localAudio",
        remoteVideoTarget: "remoteAudio",
        userMedia: {
          video: false,
          audio: true
        }
      });
      
      conn.on("connectChannel", function(channelId){
        document.getElementById("channelId").value = channelId;
      });
      document.getElementById("createChannel").onclick = function(e){
        conn.createChannel();
        return false;
      };
      document.getElementById("connectChannel").onclick = function(e){
        var channelId = document.getElementById("channelId").value;
        if(!channelId)return;
        conn.connectChannel(channelId);
        return false;
      };
    </script>
  <% elsif user_signed_in? %>
    <% if @current_user_voice.present? %>
      <script src="http://www.playrtc.com/sdk/js/1.0.6/playrtc.min.js"></script>
      <%= link_to '발언권 철회', talk_concert_voices_path(@talk_concert), method: :delete, class: "btn btn-danger" %>
      <div>
        <input type="text" id="channelId" placeholder="ChannelId를 입력하세요." value="">
        <button id="connectChannel">채널 입장</button>
        <button id="createChannel">채널 생성 및 입장</button>
      </div>
      <audio id="localAudio"></audio>
      <audio id="remoteAudio"></audio>
      <script type="text/javascript">
        conn = new PlayRTC({
          localVideoTarget: "localAudio",
          remoteVideoTarget: "remoteAudio",
          userMedia: {
            video: false,
            audio: true
          }
        });
        
        conn.on("connectChannel", function(channelId){
          document.getElementById("channelId").value = channelId;
        });
        document.getElementById("createChannel").onclick = function(e){
          conn.createChannel();
          return false;
        };
        document.getElementById("connectChannel").onclick = function(e){
          var channelId = document.getElementById("channelId").value;
          if(!channelId)return;
          conn.connectChannel(channelId);
          return false;
        };
      </script>
    <% else %>
      <%= link_to '발언권 신청', talk_concert_voices_path(@talk_concert), method: :create, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/talk_concerts/show.html.erb
<% provide(:title, @talk_concert.title) %>
<h1><%= @talk_concert.title %></h1>
<table class="table table-striped">
  <tbody>
    <tr>
      <td>강연자</td>
      <td><%= @talk_concert.user.name %></td>
    </tr>
    <tr>
      <td>시작시간</td>
      <td><%= @talk_concert.start_time %></td>
    </tr>
    <tr>
      <td>종료시간</td>
      <td><%= @talk_concert.end_time %></td>
    </tr>
    <tr>
      <td>장소</td>
      <td><%= @talk_concert.location %></td>
    </tr>
    <tr>
      <td>인원제한</td>
      <td><%= @talk_concert.people_limit %></td>
    </tr>
    <tr>
      <td>내용</td>
      <td><%= @talk_concert.content %></td>
    </tr>
    <tr>
      <td>참여시작시간</td>
      <td><%= @talk_concert.enroll_start_time %></td>
    </tr>
    <tr>
      <td>참여종료시간</td>
      <td><%= @talk_concert.enroll_end_time %></td>
    </tr>
  </tbody>
</table>

<h2>참여자 목록</h2>
<div class="container">
  <%= render @enrollments %>
</div>

<%= link_to '목록', talk_concerts_path, class: "btn btn-primary" %>
<% if user_signed_in? && current_user.can_update?(@talk_concert) %>
  <%= link_to '수정', edit_talk_concert_path(@talk_concert), class: "btn btn-primary" %>
  <%= link_to '삭제', @talk_concert, method: :delete, data: { confirm: '정말 삭제하시겠습니까?' }, class: "btn btn-danger" %>
<% end %>

<% if user_signed_in? %>
  <% if current_user == @talk_concert.user %>
    <%= link_to '방 입장', room_talk_concert_path(@talk_concert), class: "btn btn-success" %>
  <% elsif @current_user_enrollment.present? %>
    <%= link_to '참여 철회', talk_concert_enrollments_path(@talk_concert), method: :delete, class: "btn btn-danger" %>

    <%= link_to '방 입장', room_talk_concert_path(@talk_concert), class: "btn btn-success" %>
  <% else %>
    <%= link_to '참여 신청', talk_concert_enrollments_path(@talk_concert), method: :create, class: "btn btn-primary" %>
  <% end %>
<% end %>